name: Node.js Package

on:
  pull_request:
    branches:
      - master
      - Release
  push:
    branches:
      - master
      - Release
      - refs/tags/*
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - name: Create code coverage report
        run: yarn test:coverage
      - name: Change Report Path
        run: sed -i 's+/home/runner/work/ccd-case-ui-toolkit/ccd-case-ui-toolkit+/github/workspace+g' coverage/lcov.info
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: coverage

  sonarcloud:
    needs: build
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Download code coverage results
      uses: actions/download-artifact@v1
      with:
        name: code-coverage-report
        path: coverage
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
